name: DevSecOps Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and run hello.py
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run hello.py
        run: python hello.py

      # Step 3: Install Bandit and run security scan on Python code
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r .

      # Step 4: Build Docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true          # 👈 important, makes image available locally
          tags: devsecops-demo:latest

      # Step 5: Show docker images (to confirm build worked)
      - name: Show docker images
        run: docker images

      # Step 6: Run Trivy scan on the image
      - name: Run Trivy vulnerability scan on built image
        run: trivy image --format table --severity CRITICAL,HIGH,MEDIUM devsecops-demo:latest
