name: DevSecOps Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run hello.py
        run: python hello.py

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r .

      # --- Docker build steps ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false           # do NOT push to any registry
          tags: devsecops-demo:latest

      # --- Trivy scan ---
      - name: Run Trivy vulnerability scan on built image
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: devsecops-demo:latest
          format: 'table'       # human readable; change if needed
          severity: 'CRITICAL,HIGH,MEDIUM'  # show important severities
