name: DevSecOps Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run hello.py
        run: python hello.py

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r .

      # Docker build preparation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image (local only)
      - name: Build Docker image (local only)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: devsecops-demo:latest

      # Install Trivy CLI (alternative to trivy-action)
      - name: Install Trivy CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy-archive-keyring.gpg
          echo deb [signed-by=/usr/share/keyrings/trivy-archive-keyring.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      # Run Trivy against the locally-built image
      - name: Run Trivy vulnerability scan on built image
        run: |
          echo "Scanning local image: devsecops-demo:latest"
          trivy image --format table --severity CRITICAL,HIGH,MEDIUM devsecops-demo:latest
