name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (local only)
        run: docker build -t devsecops-demo:latest .

      - name: Show docker images
        run: docker images

      # ✅ Add Trivy install step here
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      # ✅ Trivy scan step (now Trivy is available)
      - name: Run Trivy vulnerability scan on built image
        run: trivy image --format table --severity CRITICAL,HIGH,MEDIUM devsecops-demo:latest
